### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by matyj** [lmller/gof-in-kotlin#2]
I couldn't comment your post, so I'll try here. 
Hi, 
I really enjoyed reading your post, those very commonly used patterns look really great in Kotlin, so thank you for your work. I'm working for some time in Kotlin already, and I'm still coding more Java-like than Kotlin-like I suppose, your post has given me some tips. However, I've got a question about using extensions. Well, afaik those functions can be used to modify the class (decorate it) to which we do not have and access (Android classes for example). What is the reason to use extensions in for example Decorator pattern while probably we could just write some class methods and use them the same way?

**Comment by lmller** [comment]
I'm sorry, I don't quite understand what your question is.
Do you want to know why we should use extension functions in the first place, or why I used it for the decorator example?

**Comment by matyj** [comment]
My question is: Why should we use extension functions instead of class methods. Both approaches mean that we're declaring a function and we can call it on an object, so I don't quite understand what's better in extensions comparing to methods. (in this case)

**Comment by lmller** [comment]
extension functions can be created for all classes, not only the ones you own (you can e.g. extend `String`) 
if you own the class, normal methods are probably better. however, even if you do own the class, extensions can be beneficial to code organization (scope) and class length.
Always consider extension functions if you would write a static Util function in java.

My decorator uses extension functions to avoid the creation of inheritance-hierarchies. However, a better way to do this is function composition. But Kotlin does not support that out-of-the-box. (https://hackernoon.com/funktionale-function-composition-for-kotlin-1f6e3e3c3a83)
